#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

permissions_config() {
    echo "**** (permissions_config) Settings permissions ****";
    mkdir -p \
        /tmp/unmanic \
        /config/.unmanic
    chown -R ${PUID}:${PGID} \
        /tmp/unmanic \
        /config/.unmanic \
        /app
    chmod -R a+w \
        /tmp/unmanic\
        /config/.unmanic \
        /app
}

permissions_config;
