#!/usr/bin/with-contenv bash

CWD=${PWD};

permissions_config() {
    echo "**** (permissions_config) Settings permissions ****";
    mkdir -p \
        /tmp/unmanic
    chown -R $PUID:$PGID \
        /tmp/unmanic \
        /config/.unmanic \
        /app
    chmod -R a+w \
        /tmp/unmanic \
        /app
}

permissions_config;
