{{- if .Values.configSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unmanic.fullname" . }}-config
  labels:
    {{- include "unmanic.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key := (keys .Values.configSecret | sortAlpha) }}
  {{ $key }}: {{ get $.Values.configSecret $key | quote }}
  {{- end }}
{{- end }}
