#!/usr/bin/with-contenv bash

RUN_USER=abc

if [[ -e /app/unmanic/service.py ]]; then
    echo "Update container to running Unmanic from source"
    if [[ ! -L /usr/local/lib/python3.8/dist-packages/unmanic ]]; then
        echo "Move container unmanic install"
        mv /usr/local/lib/python3.8/dist-packages/unmanic /usr/local/lib/python3.8/dist-packages/unmanic-installed
    fi
    ln -sf /app/unmanic /usr/local/lib/python3.8/dist-packages/unmanic
fi

unmanic_params=''
if [[ "${DEBUGGING}" == 'true' ]]; then
    unmanic_params="--dev ${unmanic_params}"
fi

chmod +x /usr/bin/unmanic
exec s6-setuidgid root /usr/bin/unmanic "${unmanic_params}"
